name: Hello World
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Print 
      run: python -c "print('Hello, world!')"
